language: go

go:
  - "1.11"

sudo: required

os:
  - linux
  - osx

env:
  global:
    - DEP_RELEASE_TAG=v0.5.0

services:
  - docker

notifications:
  email:
    recipients:
      - revett@cityofzion.io
    on_success: never
    on_failure: always

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mkdir $GOPATH/bin; fi
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - chmod +x $GOPATH/bin/dep
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cask install docker-toolbox; fi

install:
  - cd ./cli
  - dep ensure -v
  - cd ..

# Script step is run as part of a shell script as it requires a conditional.
script:
  ./scripts/travis.sh